all: first second third fourth clean

first:
	gcc -Wall -Werror -Wextra n1.c -o first
	./first

second:
	gcc -Wall -Werror -Wextra n2.c -o second
	./second

third:
	gcc -Wall -Werror -Wextra n3.c -o third
	./third

fourth:
	gcc -Wall -Werror -Wextra n4.c -o fourth
	./fourth

clean:
	rm -rf first second third fourth